/*
 * InfoInput.java
 *
 * Created on July 2, 2006, 10:28 PM
 */

package gurpsgen;
import javax.swing.*;

/**
 *
 * @author  Jac
 */
public class InfoInput extends javax.swing.JFrame {
    
    /** Creates new form InfoInput */
    public InfoInput() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        getContentPane().setLayout(new java.awt.BorderLayout(50, 50));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new java.awt.GridLayout(6, 2, 6, 6));

        jPanel1.setBorder(new javax.swing.border.TitledBorder("Solar Characteristics"));
        jLabel1.setText("Star Name");
        jPanel1.add(jLabel1);

        jTextField1.setText("Solis");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                validateName(evt);
            }
        });

        jPanel1.add(jTextField1);

        jLabel2.setText("Star Type");
        jPanel1.add(jLabel2);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "O", "B", "A", "F", "G", "K", "M", "D" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jPanel1.add(jComboBox1);

        jLabel3.setText("Star Size");
        jPanel1.add(jLabel3);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ia", "Ib", "II", "III", "IV", "V", "VI" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jPanel1.add(jComboBox2);

        jLabel4.setText("Bode Constant");
        jPanel1.add(jLabel4);

        jTextField2.setText("0.3");
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                validateName(evt);
            }
        });

        jPanel1.add(jTextField2);

        jLabel5.setText("Is it a binary star?");
        jPanel1.add(jLabel5);

        jButton3.setText("Yes");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getBinaryDetails(evt);
            }
        });

        jPanel1.add(jButton3);

        jButton2.setText("Close");
        jButton2.setMaximumSize(new java.awt.Dimension(83, 23));
        jButton2.setPreferredSize(new java.awt.Dimension(55, 23));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jPanel1.add(jButton2);

        jButton1.setText("Enter Data");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jPanel1.add(jButton1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void getBinaryDetails(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_getBinaryDetails
// TODO add your handling code here:
        //called when the user clicks on the 'yes binary' button

        Main.starDetails[4] = "yes";
        SecondStarDetails star = new SecondStarDetails();
        star.createForm();
        
    }//GEN-LAST:event_getBinaryDetails

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
// TODO add your handling code here:
        java.awt.Dimension d = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        JFrame frame = (JFrame)evt.getSource();
        frame.setLocation((d.width - frame.getSize().width) / 2, 
                (d.height -frame.getSize().height) / 2);
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
// TODO add your handling code here:

    }//GEN-LAST:event_formWindowOpened

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
// TODO add your handling code here:
        if (Main.fileOutput != null)
            Main.fileOutput.close();
        System.exit(0);
    }//GEN-LAST:event_jButton2MouseClicked

    private void validateName(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_validateName
// TODO add your handling code here:
        String starName = ((JTextField)evt.getSource()).getText();
        if (starName.length() < 1){
            JOptionPane.showMessageDialog((java.awt.Component)evt.getSource(), 
                    "You must enter a value.",
                    "Inane warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_validateName

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
// TODO add your handling code here:
        //read data from all five entry fields into array starDetails
        Main.starDetails[0] = jTextField1.getText();
        Main.starDetails[1] = (String)jComboBox1.getSelectedItem();
        Main.starDetails[2] = (String)jComboBox2.getSelectedItem();
        Main.starDetails[3] = jTextField2.getText();
        
        /*
        String binary = "no";
        if (jCheckBox1.isSelected()){
            binary = "yes";
        } 
        Main.starDetails[4] = binary;
        */
        
        //call starData
        Main.initFileOutput();
        starData star = new starData();
         //close form
        return;
    }//GEN-LAST:event_jButton1MouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
    

    public void createForm() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InfoInput().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
    
}
